export const DASHBOARD_GRAPH_DATA = {
  request: 'DASHBOARD_GRAPH_DATA_REQUEST',
  success: 'DASHBOARD_GRAPH_DATA_SUCCESS',
  fail: 'DASHBOARD_GRAPH_DATA_FAIL',
  update: 'DASHBOARD_GRAPH_DATA_UPDATE',
};

export const CLEAR_GRAPH_ERRORS = 'CLEAR_GRAPH_ERRORS';
export const RESET_GRAPH_STATE = 'RESET_GRAPH_STATE';
