export const Actions = {
  FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',
  SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
  UPDATE_NOTIFICATION_STATE: 'UPDATE_NOTIFICATION_STATE',
  RESET_STATE: 'RESET_STATE',
};
