export const STUDENT_LIST = {
  request: 'STUDENT_LIST_REQUEST',
  success: 'STUDENT_LIST_SUCCESS',
  fail: 'STUDENT_LIST_FAIL',
  update: 'STUDENT_LIST_UPDATE',
};
export const STUDENT_DETAILS = {
  request: 'STUDENT_DETAILS_REQUEST',
  success: 'STUDENT_DETAILS_SUCCESS',
  fail: 'STUDENT_DETAILS_FAIL',
  update: 'STUDENT_DETAILS_UPDATE',
};

export const ENROLLMENT_LIST = {
  request: 'ENROLLMENT_LIST_REQUEST',
  success: 'ENROLLMENT_LIST_SUCCESS',
  fail: 'ENROLLMENT_LIST_FAIL',
  update: 'ENROLLMENT_LIST_UPDATE',
};

export const ATTENDANCE_LIST = {
  request: 'ATTENDANCE_LIST_REQUEST',
  success: 'ATTENDANCE_LIST_SUCCESS',
  fail: 'ATTENDANCE_LIST_FAIL',
  update: 'ATTENDANCE_LIST_UPDATE',
};

export const DATE_WISE_ATTENDANCE = {
  request: 'DATE_WISE_ATTENDANCE_REQUEST',
  success: 'DATE_WISE_ATTENDANCE_SUCCESS',
  fail: 'DATE_WISE_ATTENDANCE_FAIL',
};

export const HOMEWORK_LIST = {
  request: 'HOMEWORK_LIST_REQUEST',
  success: 'HOMEWORK_LIST_SUCCESS',
  fail: 'HOMEWORK_LIST_FAIL',
  update: 'HOMEWORK_LIST_UPDATE',
};

export const UPDATE_STUDENT_STATE = 'UPDATE_STUDENT_STATE';
export const CLEAR_STUDENT_ERRORS = 'CLEAR_STUDENT_ERRORS';
export const RESET_STUDENT_STATE = 'RESET_STUDENT_STATE';
