export const SUBJECTS_LIST = {
  request: 'SUBJECTS_LIST_REQUEST',
  success: 'SUBJECTS_LIST_SUCCESS',
  update: 'SUBJECTS_LIST_UPDATE',
  fail: 'SUBJECTS_LIST_FAIL',
};
export const PUBLIC_SUBJECTS_LIST = {
  request: 'PUBLIC_SUBJECTS_LIST_REQUEST',
  success: 'PUBLIC_SUBJECTS_LIST_SUCCESS',
  fail: 'PUBLIC_SUBJECTS_LIST_FAIL',
};

export const PUBLIC_SUBJECT_DETAIL = {
  request: 'PUBLIC_SUBJECT_DETAIL_REQUEST',
  success: 'PUBLIC_SUBJECT_DETAIL_SUCCESS',
  fail: 'PUBLIC_SUBJECT_DETAIL_FAIL',
};

export const UPDATE_SUBJECT_STATE = 'UPDATE_SUBJECT_STATE';
export const CLEAR_SUBJECT_ERRORS = 'CLEAR_SUBJECTS_ERRORS';
export const RESET_SUBJECT_STATE = 'RESET_SUBJECTS_STATE';
