export const SUBJECTS_LIST = {
  request: 'SUBJECTS_LIST_REQUEST',
  success: 'SUBJECTS_LIST_SUCCESS',
  update: 'SUBJECTS_LIST_UPDATE',
  fail: 'SUBJECTS_LIST_FAIL',
};
export const CLEAR_SUBJECT_ERRORS = 'CLEAR_SUBJECTS_ERRORS';
export const RESET_SUBJECT_STATE = 'RESET_SUBJECTS_STATE';
