export const CONTACT_FORM_LIST = {
  request: 'CONTACT_FORM_LIST_REQUEST',
  success: 'CONTACT_FORM_LIST_SUCCESS',
  fail: 'CONTACT_FORM_LIST_FAIL',
};

export const CLEAR_CONTACT_FORM_ERRORS = 'CLEAR_CONTACT_FORM_ERRORS';
export const RESET_CONTACT_FORM_STATE = 'RESET_CONTACT_FORM_STATE';
