export const GET_NOTE_DETAILS = 'GET_NOTE_DETAILS';
export const GET_NOTES_LIST = 'GET_NOTES_LIST';
export const CLEAR_BUILDER_ERRORS = 'CLEAR_BUILDER_ERRORS';
export const RESET_BUILDER_STATE = 'RESET_BUILDER_STATE';
