export const Actions = {
  CHAT_MODEL: 'CHAT_MODEL',
  FETCH_SESSION_DETAILS: 'FETCH_SESSION_DETAILS',
  SET_SESSION_ID: 'SET_SESSION_ID',
  UPDATE_CHAT_AGENT_STATE: 'UPDATE_CHAT_AGENT_STATE',
  RESET_STATE: 'RESET_STATE',
};
